# Generated by Django 4.1.6 on 2023-02-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhavenapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed')], default='in-progress', max_length=20),
        ),
    ]
