# Generated by Django 4.1.6 on 2023-02-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhavenapi', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='products',
            field=models.ManyToManyField(through='greenhavenapi.ProductDesign', to='greenhavenapi.product'),
        ),
    ]
