# Generated by Django 4.1.7 on 2023-03-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhavenapi', '0002_alter_design_room_alter_design_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='room',
            field=models.TextField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('office', 'Office'), ('bathroom', 'Bathroom')], max_length=200),
        ),
        migrations.AlterField(
            model_name='design',
            name='style',
            field=models.TextField(choices=[('modern', 'Modern'), ('industrial', 'Industrial'), ('bohemian', 'Bohemian'), ('farmhouse', 'Farmhouse'), ('traditional', 'Traditional'), ('midcentury_modern', 'Midcentury Modern')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
