# Generated by Django 4.1.3 on 2023-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhavenapi', '0004_alter_productorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
