# Generated by Django 4.1.7 on 2023-03-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhavenapi', '0005_design_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='design',
            name='room',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('office', 'Office'), ('bathroom', 'Bathroom')], max_length=50),
        ),
        migrations.AlterField(
            model_name='design',
            name='style',
            field=models.CharField(choices=[('modern', 'Modern'), ('industrial', 'Industrial'), ('bohemian', 'Bohemian'), ('farmhouse', 'Farmhouse'), ('traditional', 'Traditional'), ('midcentury_modern', 'Midcentury Modern')], max_length=50),
        ),
    ]
