# Generated by Django 4.1.7 on 2023-03-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhavenapi', '0006_alter_design_image_url_alter_design_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='design',
            name='image_url',
            field=models.TextField(max_length=500),
        ),
    ]
